const LETTERS_ROMAIN = {"M": 1000, "D": 500, "C": 100, "L" :50, "X" :10, "V":5, "I" : 1};
const REGEX_EXPRESSION_LETTERS = /^[MDCLXVI)(]+$/;
const REGEX_EXPRESSION_ORDER = /^M{0,4}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$/;

module.exports = {LETTERS_ROMAIN,REGEX_EXPRESSION_LETTERS,REGEX_EXPRESSION_ORDER};